### ISSUE TITLE
Remove padding from mobile client

### ISSUE THREAD

**Issue by dandaka** [oupala/apaxy#29]
Sorry, I can't do pull requests yet. But here's quick workaround to remove padding from mobile screens.

```css
body {
    padding:0;
    -webkit-backface-visibility:hidden;
}

@media (min-width: 768px) {
    body {
        padding:20px;
        -webkit-backface-visibility:hidden;
    }
}
```
